---
- name: Update Packages
  become: yes
#  become_user: root
  hosts: lotrun02
  gather_facts: false
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
